services:

  web:
    container_name: barcap
    image: mrunixmaxi/barcap:1.0
    #image: mrunixmaxi/barcap
    environment:
     - JAVA_OPTS=-XX:-UseContainerSupport
    restart: always
    ports:
     - "8080:8080"
    depends_on:
     - db
    networks:
     - red-backend
    hostname: backend
  db:
    image: mysql:5.7
    container_name: barcitodb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      # Use these to automatically create the DB and root user
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: barcitodb
      MYSQL_PASSWORD: admin
      MYSQL_USER: admin
    ports:
      - "3306:3306"
    networks:
      - red-backend
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    hostname: db

volumes:
  mysql_data:
 
networks:
  red-backend:
    driver: bridge